# Generated by Django 5.2.13 on 2026-04-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_passwordresetotp_passwordresettemp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetTemp',
        ),
    ]
